"""Starting catalogue, translated from the old assets/js/products.js.

Prices are rupees here and converted to paise on import. Stock counts are a
placeholder (DEFAULT_STOCK) — set real numbers in Admin → Catalogue.
Drafts and Academy shells are imported switched off, so nothing appears on the
storefront until it has a real price, photos and (for courses) lessons.
"""

DEFAULT_STOCK = 5

CATEGORIES = [
    ("texture-acrylic-paintings", "Texture & Acrylic Paintings", 1),
    ("clay-desk-decor", "Clay Desk Decor", 2),
    ("keychains-magnets", "Keychains & Magnets", 3),
    ("diy-kits", "DIY Kits", 4),
    ("masterclasses", "Masterclasses", 5),
    ("workshops", "Live Workshops", 6),
]

READY_NOTE = "Ready-to-buy design. Sold as displayed, without customisation."

PRODUCTS = [
    {
        "id": "rtb-ta-03",
        "kind": "physical",
        "category": "texture-acrylic-paintings",
        "title": "Van Gogh 'Starry Night' 3D Textured Art",
        # The old file listed price 1 (a leftover test value) against 3200; 3200 is the only real figure recorded.
        "price": 3200,
        "compare_at": None,
        "size": "10 x 12 inches",
        "material": "Heavy impasto knife texture paste & fine acrylics",
        "badge": "Masterpiece",
        "rating": 5.0,
        "reviews": 19,
        "description": "Tactile 3D textured reinterpretation of Van Gogh's Starry Night with thick impasto swirl relief.",
        "details": [
            "Fixed size: 10 x 12 inches",
            "Materials: heavy impasto paste, deep cobalt & cadmium yellow acrylics",
            "Varnished gloss protective seal",
            READY_NOTE,
        ],
        "images": ["brand_starry_night.jpg", "van_gogh_starry_night_texture.jpg"],
        "featured": True,
    },
    {
        "id": "rtb-km-mango-crate",
        "kind": "physical",
        "category": "keychains-magnets",
        "title": "Miniature Alphonso Mangoes Wooden Crate Sculpture",
        "price": 799,
        "compare_at": 999,
        "size": "6 x 5 x 5 cm",
        "material": "Sculpted polymer clay mangoes in a wooden crate",
        "badge": "Collector Special",
        "rating": 5.0,
        "reviews": 47,
        "description": "Ultra-detailed miniature wooden crate filled with ripe Alphonso mangoes, straw grass, and wooden crate structure.",
        "details": [
            "Fixed size: 6 x 5 x 5 cm",
            "Materials: polymer clay mini mangoes, natural straw, wooden crate frame",
            "Glossy resin finish on mangoes for a realistic look",
            READY_NOTE,
        ],
        "images": ["promo_mango_crate.jpg"],
        "featured": True,
    },
    {
        "id": "rtb-km-flatlay",
        "kind": "physical",
        "category": "keychains-magnets",
        "title": "Miniature Food & Clay Magnet Showcase Set",
        "price": 1299,
        "compare_at": 1599,
        "size": "Assorted set of miniatures",
        "material": "Polymer clay miniatures & neodymium magnets",
        "badge": "Gift Set",
        "rating": 5.0,
        "reviews": 38,
        "description": "Charming miniature food collection including mini pizza, dosa, orange slice, cat showpiece, and mini photo frame.",
        "details": [
            "Includes mini food magnets & table decor pieces",
            "Materials: polymer clay, resin glaze, neodymium rear magnets",
            READY_NOTE,
        ],
        "images": ["promo_flatlay_showcase.jpg"],
        "featured": True,
    },
    {
        "id": "rtb-cdd-01",
        "kind": "physical",
        "category": "clay-desk-decor",
        "title": "Harry Potter Desk Calendar",
        "price": 1499,
        "compare_at": 1799,
        "size": "14 x 10 x 6 cm",
        "material": "Sculpted clay base with interchangeable wooden date blocks",
        "badge": "Flagship Product",
        "rating": 5.0,
        "reviews": 48,
        "description": "Hand-sculpted Gryffindor Harry Potter desk calendar with mini Hedwig owl and movable wooden month & date blocks.",
        "details": [
            "Fixed dimensions: 14 cm wide x 10 cm tall",
            "Materials: high-grade air-dry clay, wooden date cubes, gloss varnish",
            "Includes all 12 wooden month tiles and 2 date cubes for perpetual use",
            READY_NOTE,
        ],
        "images": ["harry_potter_calendar_1.jpg", "harry_potter_calendar_2.jpg"],
        "featured": True,
    },
    {
        "id": "diy-kit-01",
        "kind": "kit",
        "category": "diy-kits",
        "title": "DIY Paint-Your-Own Harry Potter Desk Calendar Kit",
        "price": 999,
        "compare_at": 1299,
        "size": "14 x 10 cm raw clay figure + 6 wooden blocks",
        "material": "Unpainted primed air-dry clay figure & raw wood cubes",
        "badge": "Complete DIY Kit",
        "rating": 4.9,
        "reviews": 33,
        "description": "Receive a raw, primed Harry Potter clay sculpture with Hedwig owl and blank wooden date blocks to paint in your own favourite colours.",
        "includes": [
            "1 primed unpainted Harry Potter clay figure base",
            "6 blank wooden date & month blocks",
            "12 pots of quick-dry acrylic paint",
            "2 synthetic paintbrushes (detail & flat)",
            "1 glossy clear topcoat varnish pod",
            "1 step-by-step colour guide & instruction sheet",
        ],
        "tools_info": "All paints, brushes, varnish and tools are included. Nothing else to buy.",
        "images": ["harry_potter_calendar_1.jpg"],
    },
    {
        "id": "diy-kit-02",
        "kind": "kit",
        "category": "diy-kits",
        "title": "DIY Paint-Your-Own Ghost Incense Burner Kit",
        "price": 699,
        "compare_at": 899,
        "size": "10 cm tall raw terracotta figure",
        "material": "Primed heat-resistant clay figurine",
        "badge": "Fun DIY",
        "rating": 5.0,
        "reviews": 28,
        "description": "Paint your own cute ghost incense burner — choose the colours of its hat, sunglasses, purse and outfit.",
        "includes": [
            "1 raw primed ghost clay figure with hat & purse details",
            "6 acrylic paint pots (red, black, white, yellow, blue, pink)",
            "1 paintbrush",
            "5 natural lavender incense cones",
            "1 sealer varnish pod & instruction guide",
        ],
        "tools_info": "Paints, brush, sealant and incense cones included.",
        "images": ["brand_ghost_close.png", "ghost_incense_burner.jpg"],
    },
    {
        "id": "diy-kit-03",
        "kind": "kit",
        "category": "diy-kits",
        "title": "DIY 3D Texture Painting Canvas Starter Kit",
        "price": 1299,
        "compare_at": 1599,
        "size": "8 x 10 inch canvas",
        "material": "Gallery-stretched canvas & professional texture paste",
        "badge": "Starter Kit",
        "rating": 5.0,
        "reviews": 45,
        "description": "Learn 3D texture art at home: canvas, impasto texture paste, palette knives and paints to create your own sunflower or tulip texture canvas.",
        "includes": [
            "1 stretched gallery canvas, 8 x 10 inches",
            "1 250 g jar of impasto texture paste",
            "3 plastic palette knives in different blade shapes",
            "6 acrylic paint tubes",
            "1 stencil guide pattern & video tutorial link",
        ],
        "tools_info": "Complete starter set with palette knives, paste, canvas and colours included.",
        "images": ["texture_paste_sketching.jpg", "brand_starry_night.jpg"],
    },
    {
        "id": "diy-kit-04",
        "kind": "kit",
        "category": "diy-kits",
        "title": "DIY Paint-Your-Own Clay Ashtray / Trinket Tray Kit",
        "price": 599,
        "compare_at": 799,
        "size": "12 x 10 cm clay tray",
        "material": "Raw moulded heavy clay dish",
        "badge": "Craft Kit",
        "rating": 4.8,
        "reviews": 21,
        "description": "A blank moulded clay tray ready for your own artwork, quotes or superhero theme.",
        "includes": [
            "1 smooth unpainted clay tray base",
            "6 acrylic paint pods",
            "1 high-gloss water-resistant sealer pod",
            "2 paintbrushes",
            "1 mixing palette & sandpaper strip",
        ],
        "tools_info": "Paints, brushes and sealer included.",
        "images": ["spiderman_ashtray_trinket.jpg"],
    },
    {
        "id": "diy-kit-05",
        "kind": "kit",
        "category": "diy-kits",
        "title": "DIY Miniature Food Magnet Painting Kit (Set of 3)",
        "price": 749,
        "compare_at": 949,
        "size": "Set of 3 mini bases (~5 cm each)",
        "material": "White moulded mini clay food shapes & magnets",
        "badge": "Set of 3",
        "rating": 4.9,
        "reviews": 39,
        "description": "Paint 3 miniature food magnets — dosa platter, pizza slice and burger — and attach neodymium magnets for your fridge.",
        "includes": [
            "3 raw moulded clay food mini bases",
            "3 strong neodymium magnets + craft glue",
            "8 micro acrylic paint pods",
            "1 fine detail paintbrush",
            "1 high-gloss resin topcoat",
        ],
        "tools_info": "Magnets, glue, paints, brush and glaze included.",
        "images": ["miniature_food_platters.jpg"],
    },
]

# Pieces photographed in assets/images and named in the business plan but never listed for sale.
# Imported switched off; each needs a price (and stock) before it can go live.
DRAFTS = [
    {
        "id": "draft-white-tulips",
        "kind": "physical",
        "category": "texture-acrylic-paintings",
        "title": "White Textured Tulips Canvas",
        "price": 1299,  # the price charged in the one order on record
        "size": "",
        "description": "3D textured relief canvas of white tulips.",
        "images": ["white_textured_tulips_canvas.jpg", "tulips_relief_canvas.jpg"],
    },
    {
        "id": "draft-shiva-relief",
        "kind": "physical",
        "category": "texture-acrylic-paintings",
        "title": "Lord Shiva 3D Relief Round Canvas",
        "price": 0,
        "size": "",
        "description": "Round 3D relief canvas of Lord Shiva with rudraksha bead details and crescent moon.",
        "images": ["brand_shiva_art.jpg"],
    },
    {
        "id": "draft-sun-calendar",
        "kind": "physical",
        "category": "clay-desk-decor",
        "title": "Sun Perpetual Desk Calendar",
        "price": 0,
        "size": "",
        "description": "Hand-sculpted clay sun perpetual calendar.",
        "images": ["new_sun_calendar.jpg"],
    },
    {
        "id": "draft-character-trinket-dishes",
        "kind": "physical",
        "category": "clay-desk-decor",
        "title": "Character Clay Trinket Dishes",
        "price": 0,
        "size": "",
        "description": "Hand-painted clay trinket dishes with character designs.",
        "images": ["we_bare_bears_trinket_dishes.jpg", "marlboro_spiderman_trinket_flatlay.jpg"],
    },
    {
        "id": "draft-sunflower-coasters",
        "kind": "physical",
        "category": "clay-desk-decor",
        "title": "Sunflower Clay Coasters",
        "price": 0,
        "size": "",
        "description": "Textured sunflower coasters in hand-painted clay.",
        "images": ["sunflower_coaster_mini.jpg"],
    },
    {
        "id": "draft-magnet-collection",
        "kind": "physical",
        "category": "keychains-magnets",
        "title": "Miniature Magnet Collection",
        "price": 0,
        "size": "",
        "description": "Hand-sculpted miniature clay magnets.",
        "images": ["red_heart_magnet.jpg", "miniature_veggie_platter.jpg"],
    },
]

# Academy shells from the business plan. No lessons, no price: build the curriculum in Admin → Academy.
COURSES = [
    {
        "id": "course-texture-paste",
        "title": "Texture Paste Formulation Masterclass",
        "description": "Pre-recorded video lessons on mixing your own texture paste and building it up in layers.",
        "level": "Beginner",
        "images": ["texture_paste_sketching.jpg"],
    },
    {
        "id": "course-palette-knife",
        "title": "Palette Knife Sculpting Masterclass",
        "description": "Pre-recorded video lessons on sculpting relief texture with palette knives.",
        "level": "Intermediate",
        "images": ["paint_palette_detail.jpg"],
    },
    {
        "id": "course-metallic-gilding",
        "title": "Metallic Gilding Masterclass",
        "description": "Pre-recorded video lessons on adding metallic and gold accents to textured work.",
        "level": "Intermediate",
        "images": ["textured_journal_gold_flower.jpg"],
    },
]

WORKSHOPS = [
    {
        "id": "workshop-weekend-texture",
        "title": "Live Weekend Texture Art Workshop",
        "description": "A live online weekend class with a limited number of seats.",
        "images": ["sunflower_texture_painting.jpg"],
    },
]

# Codes the old checkout accepted. Kept so nothing a customer was told stops working.
COUPONS = [
    {"code": "RANGDHAARA10", "kind": "percent", "value": 10},
    {"code": "WELCOME50", "kind": "flat", "value": 5000},
]
